<?php

namespace ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
	public function getProjectsByUser($userId)
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT p 
			FROM ProjectBundle:Project p 
			JOIN p.team_members t 
			JOIN t.users u 
			WHERE u.id = :userId')
		->setParameter('userId', $userId);

		return $query->getResult();
	}
}
